### ISSUE TITLE
After import, the "All Posts" page is empty.

### ISSUE THREAD

**Issue by kirillrocks** [glebnikolaev/ja-mport#3]
After import, the "All Posts" page is empty, but posts statistics are correct.

image for reference:
https://dl.dropboxusercontent.com/s/p6lfkg7lp7rry2p/chrome_2017-05-14_10-34-48.png

**THE ERRORS OCCURS ONLY WITH BIG FILES**
**3000 rows test file:** https://www.dropbox.com/s/jks1vuyehhwjtfc/SAMPLE2.csv?dl=0

**Comment by glebnikolaev** [comment]
Не удалось воспроизвести ошибку
Первый раз импортировал test file: https://yadi.sk/i/gDQFnA_g3J93fE
Сразу же зашел на страницу all posts: https://yadi.sk/i/CRS3vJxO3J94Fs
Попытка импортировать второй раз этот же файл: https://yadi.sk/i/5OKgBdx63J94KF

**Comment by kirillrocks** [comment]
did yoy check the big file I added? 3000 rows

**Comment by glebnikolaev** [comment]
Yes! I use your sample file from first message
